default: &default
  USER_CAMERON: 'user_7yeC8Gy5Lsy5Q3ZIoqnjqHafaLelkKCVwLwt3jxzbIW'
  USER_JIAQI: 'user_wmTtd8nV52aR4wWuomPcBjEvp2mtDzMi4MBenCVC9AT'
  USER_NINA: 'user_2ZGOJlgHLy7JZmJf42VvrAXG9XyW4jH2sXJ3H2QXDmC'
  USER_CHAR: 'user_NxQLw8bCCkgUsKRC9tZIEKRrDsnUf0ru4qiM3gL3Gb6'
  USER_JASMINE: 'user_2ceDTwvSHCyIIZ7ngOBO8yT7UHEnOESsusgOKeIuzjH'
  SEQUENCE_EMAIL_ASSESSMENT: 'seq_7AnyaSgTQ1phlcPsGZMHSY'
  SEQUENCE_INVITATION: 'seq_77Ldw94n17y7a8PSi6dmd0'
  TEMPLATE_ORIENTATION_PDX_FT: 'tmpl_Tw0GKZnJM93xOfaRE2gJS7M3iFhyVw6OXhDu4eFUNsL'
  TEMPLATE_ORIENTATION_SEA_FT: 'tmpl_brmmxvr7KY3QRilBki1npFdte5BaIHvJUZmA7eCZauV'
  TEMPLATE_ORIENTATION_WEB_FT: 'tmpl_QjbKkarsgRlSMLSYuPIHHncFrj0fr0ZivVSKxf0rwP6'
  TEMPLATE_ORIENTATION_PDX_PT_INTRO: 'tmpl_QIXggiECxZqdgeBqozEeADizXK8eLZMa9AbQyFrscV1'
  TEMPLATE_ORIENTATION_SEA_PT_INTRO: 'tmpl_DZRZQ9adlRgicQ1a85jmmhesOplSFsjIxkbIdAwsVCm'
  TEMPLATE_ORIENTATION_WEB_PT_INTRO: 'tmpl_BtijbYn3dH0goBS9PJ1F8U00ApPgqUXiBpBhR73dxQU'
  TEMPLATE_ORIENTATION_PDX_PT_FULL_STACK: 'tmpl_yacVO0oIzSeV2XTA7h4hbvcyvKyaMFyzJBWy1wrxvzE'
  TEMPLATE_ORIENTATION_SEA_PT_FULL_STACK: 'tmpl_E9erE3WVKHb6PBc6R69wcw9YCaVQoqfIOVL1BXfqeJQ'
  TEMPLATE_ORIENTATION_WEB_PT_FULL_STACK: 'tmpl_Mg9fneIEyI3hQlOXXrjEJ5TIF5vbYKbfMEjNCX7dXaO'

test:
  <<: *default

development:
  <<: *default
